name: 'Build and Push Docker Image with Release'
description: 'Builds a Docker image and pushes it to Docker Hub, then creates a GitHub release and sends Telegram notifications.'
author: 'Yuri V <yuri.valigursky@gmail.com> (@yuri-val)'

branding:
  icon: 'upload-cloud'
  color: 'orange'

inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true
  telegram_to:
    description: 'Telegram recipient/chat ID'
    required: true
  telegram_token:
    description: 'Telegram bot token'
    required: true
  docker_hub_username:
    description: 'Docker Hub username'
    required: true
  docker_hub_access_token:
    description: 'Docker Hub access token'
    required: true
  docker_repo_name:
    description: 'Docker Hub repository name'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Extract repository name
      shell: bash
      run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)" >> $GITHUB_ENV

    - name: Send Telegram Message on Start
      uses: appleboy/telegram-action@master
      continue-on-error: true
      with:
        to: ${{ inputs.telegram_to }}
        token: ${{ inputs.telegram_token }}
        format: html
        message: "💬 <b>STARTED</b>: build <pre>${{ github.repository }}</pre>"

    - name: Get Current Date
      shell: bash
      id: date
      run: echo "date=$(date +'%y.%m.%d.%H%M')" >> $GITHUB_OUTPUT

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Get Current Commit SHA
      shell: bash
      id: get_sha
      run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_hub_username }}
        password: ${{ inputs.docker_hub_access_token }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: |
          ${{ inputs.docker_hub_username }}/${{ inputs.docker_repo_name }}:${{ steps.date.outputs.date }}
          ${{ inputs.docker_hub_username }}/${{ inputs.docker_repo_name }}:latest
        build-args: |
          COMMIT_SHA=${{ steps.get_sha.outputs.sha }}
          TAG_VERSION=${{ steps.date.outputs.date }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache

    - name: Bump Version and Push Tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ inputs.github_token }}
        custom_tag: ${{ steps.date.outputs.date }}
        tag_prefix: ""

    - name: Get previous tag
      id: get_previous_tag
      shell: bash
      run: |
        git fetch --tags --force --quiet
        PREVIOUS_TAG=$(git describe --tags --abbrev=0 "${{ steps.tag_version.outputs.new_tag }}"^ || echo "")
        echo "PREVIOUS_TAG=$PREVIOUS_TAG" >> $GITHUB_OUTPUT

    - name: Generate changelog
      id: generate_changelog
      shell: bash
      run: |
        if [ -n "${{ steps.get_previous_tag.outputs.PREVIOUS_TAG }}" ]; then
          CHANGELOG=$(git log --pretty=format:"- %B" "${{ steps.get_previous_tag.outputs.PREVIOUS_TAG }}..${{ steps.tag_version.outputs.new_tag }}")
        else
          CHANGELOG=$(git log --pretty=format:"- %B" "${{ steps.tag_version.outputs.new_tag }}")
        fi
        CHANGELOG=$(echo "$CHANGELOG" | sed -e ':a' -e 'N' -e '$!ba' -e 's/\n\+$/\n/')
        echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Create a GitHub Release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ inputs.github_token }}
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Build ${{ steps.date.outputs.date }}
        body: ${{ steps.generate_changelog.outputs.CHANGELOG }}

    - name: Send Telegram Message on Success
      if: ${{ success() }}
      uses: appleboy/telegram-action@master
      continue-on-error: true
      with:
        to: ${{ inputs.telegram_to }}
        token: ${{ inputs.telegram_token }}
        format: html
        message: "✅ <b>SUCCESSFUL</b>: built <pre>${{ github.repository }}</pre> version <pre>${{ steps.date.outputs.date }}</pre>"

    - name: Send Telegram Message on Failure
      if: ${{ failure() }}
      uses: appleboy/telegram-action@master
      continue-on-error: true
      with:
        to: ${{ inputs.telegram_to }}
        token: ${{ inputs.telegram_token }}
        format: html
        message: "❌ <b>FAIL</b>: build failed for <pre>${{ github.repository }}</pre>"
